package com.example.flat2d.Misc;
/*
    ENUM FOR DIFFERENT TYPES OF ENTITIES THIS ENUM MAINLY FOCUSES ON ENTITIES LIKE THE
    ENEMIES, PLAYER AND EXP AND SKILLS
 */
public enum EntityType {
    //PLAYER RELATED
    PLAYER, WALL, ENEMY, SMALL_EXP, MEDIUM_EXP, BIG_EXP, BASICSKILL, ORATRICE, SMOL_BOMB, MID_BOMB
    //ENEMIES
    ,WOLF, HELLHOUND, GHOST,FIRESKULL,BOSS, HELLBEAST, BIG_BOMB, FORESKIN_DRAGON
}
